export const mapJZtoEPB = (jzBody: any) => {
  return {
    amount: Number(jzBody.amount),              // REQUIRED
    phone: jzBody.phone,                // REQUIRED, normalized to start with 92
    order_id: jzBody.order_id || undefined,    // OPTIONAL, autogenerated if not provided
    bankCode: jzBody.bankCode,                 // REQUIRED for bank identification
    accountNo: jzBody.iban,                    // REQUIRED, IBAN / account number
    purpose: jzBody.purpose || "0350",       // OPTIONAL, default purpose if not provided
  };
};


const normalizePhone = (phone: string) => {
  if (phone.startsWith("03")) {
    return "92" + phone.slice(1);
  }
  return phone;
};
